name: Setup Doppler
description: Set up Doppler CLI and authenticate with your Doppler account.

inputs:
  doppler_token:
    description: 'Doppler service token for authentication.'
    required: true
  environment:
    description: 'Doppler environment to use.'
    required: true
  project:
    description: 'Doppler project to use.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Doppler CLI
      shell: bash
      run: |
        # Install Doppler CLI using sudo
        sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates curl gnupg
        curl -sLf --retry 3 --tlsv1.2 --proto "=https" 'https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key' | sudo gpg --dearmor -o /usr/share/keyrings/doppler-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/doppler-archive-keyring.gpg] https://packages.doppler.com/public/cli/deb/debian any-version main" | sudo tee /etc/apt/sources.list.d/doppler-cli.list
        sudo apt-get update && sudo apt-get install -y doppler

    - name: Fetch secrets from Doppler
      shell: bash
      run: |
        doppler secrets download --no-file --format env > doppler.env
        cat doppler.env >> $GITHUB_ENV
      env:
        DOPPLER_TOKEN: ${{ inputs.doppler_token }}
        DOPPLER_PROJECT: ${{ inputs.project }}
        DOPPLER_CONFIG: ${{ inputs.environment }}