name: Setup Doppler
description: Set up Doppler CLI and authenticate with your Doppler account.

inputs:
  doppler_token:
    description: 'Doppler service token for authentication.'
    required: true
  environment:
    description: 'Doppler environment to use.'
    required: true
  project:
    description: 'Doppler project to use.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Doppler CLI
      shell: bash
      run: |
        # Install Doppler CLI
        curl -Ls https://cli.doppler.com/install.sh | sh

    - name: Fetch secrets from Doppler
      shell: bash
      run: |
        doppler secrets download --no-file --format env > doppler.env
        cat doppler.env >> $GITHUB_ENV
      env:
        DOPPLER_TOKEN: ${{ inputs.doppler_token }}
        DOPPLER_PROJECT: ${{ inputs.project }}
        DOPPLER_CONFIG: ${{ inputs.environment }}